### ISSUE TITLE
Search Services

### ISSUE THREAD

**Issue by markus-moser** [pimcore/generic-data-index-bundle#67]
```[tasklist]
### Tasks
- [ ] https://github.com/pimcore/generic-data-index-bundle/issues/66
- [x] https://github.com/pimcore/generic-data-index-bundle/issues/72
- [ ] https://github.com/pimcore/generic-data-index-bundle/issues/74
```
